required_packages <- c( 'ffbase'
   , 'LaF'
   , 'ETLUtils'
   , 'data.table'
   , 'biglm'
   , 'ggplot2'
   , 'magrittr'
   , 'dplyr'
   , 'sqldf'
   , 'RSQLite'
   , 'stringr'
   , 'ggmap'
   , 'lubridate'
   , 'e1071'
   , 'glmnet'
   , 'plyr'
   , 'networkD3'
   , 'ggmap'
   , 'dygraphs'
   , 'leaflet'
   , 'shiny'
   , 'shinyapps'
   , 'knitr'
   , 'tidyr')

lapply(required_packages, require, character = TRUE)
